name: Terraform init
description: Initialize Terraform with a Azure Blob Storage backend
inputs:
  storage-account-name:
    description: 'The name of the Azure Storage Account'
    required: true
  container-name:
    description: 'The name of the Azure Blob Storage container'
    required: false
    default: 'tfstates'
  key:
    description: 'The name of the state file'
    required: true
  resource-group-name:
    description: 'The name of the Azure Resource Group'
    required: true
  client-id:
    description: 'The client ID of the Azure Service Principal'
    required: true
  subscription-id:
    description: 'The subscription ID of the Azure Service Principal'
    required: true
  tenant-id:
    description: 'The tenant ID of the Azure Service Principal'
    required: true
  working-directory:
    description: 'The working directory'
    required: true
runs:
  using: composite
  steps:
    # https://developer.hashicorp.com/terraform/language/backend/azurerm#example-configuration-for-github
    - name: Set up Terraform backend
      working-directory: ${{ inputs.working-directory }}
      env:
        STORAGE_ACCOUNT_NAME: ${{ inputs.storage-account-name }}
        CONTAINER_NAME: ${{ inputs.container-name }}
        KEY: ${{ inputs.key }}
        RESOURCE_GROUP_NAME: ${{ inputs.resource-group-name }}
      run: |
        echo "storage_account_name = \"$STORAGE_ACCOUNT_NAME\"" > backend.tfvars
        echo "container_name = \"$CONTAINER_NAME\"" > backend.tfvars
        echo "key = \"$KEY\"" >> backend.tfvars
        echo "resource_group_name = \"$RESOURCE_GROUP_NAME\"" >> backend.tfvars
      shell: bash
    - name: Cat backend.tfvars
      working-directory: ${{ inputs.working-directory }}
      run: cat backend.tfvars
      shell: bash
    - name: Terraform init 
      working-directory: ${{ inputs.working-directory }}
      run: terraform init -backend-config=backend.tfvars -input=false
      shell: bash
      env:
        ARM_USE_OIDC: true
        ARM_CLIENT_ID: ${{ inputs.client-id }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.subscription-id }}
        ARM_TENANT_ID: ${{ inputs.tenant-id }}
