name: ArgoCD CLI install
description: Install the ArgoCD CLI
inputs:
  version:
    description: 'ArgoCD CLI version'
    default: 'latest'
runs:
  using: "composite"
  steps:
  - name: Install the latest ArgoCD CLI version
    if: ${{ inputs.version == 'latest' }}
    run: |
      curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
      sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
      rm argocd-linux-amd64
    shell: bash
  - name: Get the ArgoCD CLI needed version
    if: ${{ inputs.version != 'latest' }}
    env:
      VERSION: ${{ inputs.version }}
    run: |
      curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/${VERSION}/argocd-linux-amd64
      sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
      rm argocd-linux-amd64
    shell: bash
