name: Validate PR Name
description: Validates the name of a pull request using conventional commit types and optional user-defined scopes.

inputs:
  scopes:
    description: A comma-separated list of valid scopes. Optional.
    required: false
  github-token:
    description: GitHub token used to post a comment on the PR.
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate PR name and comment on failure
      shell: bash
      env:
        PR_NAME: ${{ github.event.pull_request.title }}
        SCOPES: ${{ inputs.scopes }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        REPO: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        echo "PR name: '$PR_NAME'"
        echo "Scopes: '$SCOPES'"

        TYPES="feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert|release|hotfix"

        if [ -z "$SCOPES" ]; then
          # No scopes provided: allow no scope or validated scope
          SCOPE_REGEX='[a-zA-Z0-9]+(-[a-zA-Z0-9]+)*'
          REGEX="^($TYPES)(\\(($SCOPE_REGEX)?\\))?!?: .+$"
        else
          # Scopes provided: validate each scope, then build regex requiring one of these scopes
          IFS=',' read -ra SCOPE_LIST <<< "$SCOPES"
          for SCOPE in "${SCOPE_LIST[@]}"; do
            if [[ ! "$SCOPE" =~ ^[a-zA-Z0-9]+(-[a-zA-Z0-9]+)*$ ]]; then
              echo "❌ Invalid scope format: '$SCOPE'"
              echo "Scopes must be alphanumeric and may include hyphens not at start or end."
              exit 1
            fi
          done
          SCOPE_PATTERN=$(echo "$SCOPES" | sed 's/,/|/g')
          REGEX="^($TYPES)(\\(($SCOPE_PATTERN)\\))?!?: .+$"
        fi

        echo "Generated regex: $REGEX"

        if [[ "$PR_NAME" =~ $REGEX ]]; then
          echo "✅ PR name matches the pattern."
        else
          echo "❌ PR name does not match the required pattern: $REGEX"

          COMMENT="❌ **PR name validation failed**
          
          Expected pattern: \`$REGEX\`
          Provided name: \`$PR_NAME\`"

          curl -s -X POST "https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER/comments" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$(jq -nc --arg body "$COMMENT" '{ body: $body }')"

          exit 1
        fi
